** 1. 将 NumPy 导入为 np，并查看版本**

难度：L1

问题：将 NumPy 导入为 np，并输出版本号


In [1]:
import numpy as np
print(np.__version__)

1.13.1


**2. 如何创建 1 维数组？**

难度：L1

问题：创建数字从 0 到 9 的 1 维数组。

期望输出：
```python
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [2]:
# method 1, recommended
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# method 2
np.array([i for i in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**3. 如何创建 boolean 数组？**

难度：L1

问题：创建所有 True 的 3×3 NumPy 数组。

In [4]:
np.ones((3,3), dtype="bool")

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

** 4. 如何从 1 维数组中提取满足给定条件的项？**

难度：L1

问题：从 arr 中提取所有奇数。

输入：
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# method 1
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [7]:
# method 2
indice = np.where(arr % 2 == 1)
arr[indice]

array([1, 3, 5, 7, 9])

** 5. 如何将 NumPy 数组中满足给定条件的项替换成另一个数值？**

难度：L1

问题：将 arr 中的所有奇数替换成 -1。

输入：
``` python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
期望输出：

```python
#> array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
```

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**6. 如何在不影响原始数组的前提下替换满足给定条件的项？**

难度：L2

问题：将 arr 中所有奇数替换成 -1，且不改变 arr。

输入：
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
期望输出：

out
```python
#> array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

arr

#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.where(arr % 2 == 1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

7. 如何重塑（reshape）数组？

难度：L1

问题：将 1 维数组转换成 2 维数组（两行）。

输入：
```python
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
期望输出
```python
#> array([[0, 1, 2, 3, 4],

#>        [5, 6, 7, 8, 9]])
```


In [13]:
arr = np.arange(10)

In [14]:
# method 1
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
# method 2
np.reshape(arr, (2, -1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**8. 如何垂直堆叠两个数组？**

难度：L2

问题：垂直堆叠数组 a 和 b。

输入：
```python
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```
期望输出：
```python
#> array([[0, 1, 2, 3, 4],

#>        [5, 6, 7, 8, 9],

#>        [1, 1, 1, 1, 1],

#>        [1, 1, 1, 1, 1]])
```

In [16]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [17]:
# method 1
np.vstack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
# method 2
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**9. 如何水平堆叠两个数组？**

难度：L2

问题：水平堆叠数组 a 和 b。

输入：
```python
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```

期望输出：
```python
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],

#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [19]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [20]:
# method 1
np.hstack((a, b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [21]:
# method 2
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

难度：L2

问题：在不使用硬编码的前提下创建以下模式。仅使用 NumPy 函数和以下输入数组 a。

输入：
```python
a = np.array([1,2,3])
```

输出:
```python
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [22]:
a = np.array([1,2,3])

In [23]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

**11. 如何获得两个 Python NumPy 数组中共同的项？**

难度：L2

问题：获取数组 a 和 b 中的共同项。

输入：
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])
```
期望输出：
```python
array([2, 4])
```

In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [25]:
np.intersect1d(a, b)

array([2, 4])

**12. 如何从一个数组中移除与另一个数组重复的项？**

难度：L2

问题：从数组 a 中移除出现在数组 b 中的所有项。

输入：
```python
a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])
```
期望输出：
```python
array([1,2,3,4])
```

In [26]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [27]:
np.setdiff1d(a, b)

array([1, 2, 3, 4])

**13. 如何获取两个数组匹配元素的位置？**

难度：L2

问题：获取数组 a 和 b 中匹配元素的位置。

输入：
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])
```
期望输出：
```python
#> (array([1, 3, 5, 7]),)
```

In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [29]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

**14. 如何从 NumPy 数组中提取给定范围内的所有数字？**

难度：L2

问题：从数组 a 中提取 5 和 10 之间的所有项。

输入：
```python
a = np.arange(15)
```
期望输出：
```python
(array([ 5, 6, 7, 8, 9, 10]),)
```

In [30]:
a = np.arange(15)

In [31]:
# method 1, use boolean mask
bool_mask = (a>=5) & (a<=10) # remember to use () & () to change the operation order.
print("bool_mask:\n{}".format(bool_mask))
a[bool_mask]

bool_mask:
[False False False False False  True  True  True  True  True  True False
 False False False]


array([ 5,  6,  7,  8,  9, 10])

In [32]:
# method 2, use np.where
indices = np.where((a>=5) * (a<=10))
print("indices:\n{}".format(indices))
a[indices]

indices:
(array([ 5,  6,  7,  8,  9, 10], dtype=int64),)


array([ 5,  6,  7,  8,  9, 10])

15. 如何创建一个 Python 函数以对 NumPy 数组执行元素级的操作？

难度：L2

问题：转换函数 maxx，使其从只能对比标量而变为对比两个数组。

输入：

```python
def maxx(x, y):

    """Get the maximum of two items"""

    if x >= y:

        return x

    else:

        return y

maxx(1, 5)
#> 5
```
期望输出：
```python
a = np.array([5, 7, 9, 8, 6, 4, 5])

b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [33]:
def maxx(x, y):

    """Get the maximum of two items"""

    if x >= y:

        return x

    else:

        return y

maxx(1, 5)
#> 5

5

In [34]:
pair_max = np.vectorize(maxx)

In [35]:
a = np.array([5, 7, 9, 8, 6, 4, 5])

b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)


array([6, 7, 9, 8, 9, 7, 5])

**16. 如何在 2d NumPy 数组中交换两个列？**

难度：L2

问题：在数组 arr 中交换列 1 和列 2。
```python
arr = np.arange(9).reshape(3,3)

arr
```

In [36]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
arr[:,[0, 2, 1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

**17. 如何在 2d NumPy 数组中交换两个行？**

难度：L2

问题：在数组 arr 中交换行 1 和行 2。
```python
arr = np.arange(9).reshape(3,3)

arr
```

In [38]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
arr[[0,2,1]]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

**18. 如何反转 2D 数组的所有行？**

难度：L2

问题：反转 2D 数组 arr 中的所有行。
```python
# Input
arr = np.arange(9).reshape(3,3)
```


In [40]:
# Input
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

**19. 如何反转 2D 数组的所有列？**

难度：L2

问题：反转 2D 数组 arr 中的所有列。
```python
# Input

arr = np.arange(9).reshape(3,3)
```

In [42]:
# Input
arr = np.arange(9).reshape(3,3)
arr 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

**20. 如何创建一个包含 5 和 10 之间随机浮点的 2 维数组？**

难度：L2

问题：创建一个形态为 5×3 的 2 维数组，包含 5 和 10 之间的随机十进制小数。

In [44]:
np.random.uniform(5, 10, size=(5, 3))

array([[ 6.94198949,  7.71081968,  6.18508839],
       [ 5.40770452,  6.67265872,  7.74192214],
       [ 7.29317053,  9.35371792,  5.40032668],
       [ 7.35594892,  7.90288594,  5.40425669],
       [ 8.01722733,  9.41172574,  6.92181315]])

**21. 如何在 Python NumPy 数组中仅输出小数点后三位的数字？**

难度：L1

问题：输出或显示 NumPy 数组 rand_arr 中小数点后三位的数字。

输入：
```python
rand_arr = np.random.random((5,3))
```


In [45]:
rand_arr = np.random.random((5,3))

In [46]:
np.set_printoptions(precision=3)
rand_arr

array([[ 0.178,  0.56 ,  0.184],
       [ 0.909,  0.226,  0.287],
       [ 0.853,  0.81 ,  0.197],
       [ 0.917,  0.46 ,  0.217],
       [ 0.793,  0.713,  0.156]])

**22. 如何通过禁用科学计数法（如 1e10）打印 NumPy 数组？**

难度：L1

问题：通过禁用科学计数法（如 1e10）打印 NumPy 数组 rand_arr。

输入：
```python
# Create the random array

np.random.seed(100)

rand_arr = np.random.random([3,3])/1e3

rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],

#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],

#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])
```

期望输出：

```python
#> array([[ 0.000543,  0.000278,  0.000425],

#>        [ 0.000845,  0.000005,  0.000122],

#>        [ 0.000671,  0.000826,  0.000137]])
```

In [47]:
# Create the random array
np.random.seed(100)

rand_arr = np.random.random([3,3])/1e3

rand_arr

array([[  5.434e-04,   2.784e-04,   4.245e-04],
       [  8.448e-04,   4.719e-06,   1.216e-04],
       [  6.707e-04,   8.259e-04,   1.367e-04]])

In [48]:
np.set_printoptions(suppress=True)

In [49]:
rand_arr

array([[ 0.001,  0.   ,  0.   ],
       [ 0.001,  0.   ,  0.   ],
       [ 0.001,  0.001,  0.   ]])

**23. 如何限制 NumPy 数组输出中项的数目？**

难度：L1

问题：将 Python NumPy 数组 a 输出的项的数目限制在最多 6 个元素。

输入：
```python
a = np.arange(15)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
```
期望输出：
```python
#> array([ 0, 1, 2, ..., 12, 13, 14])
```

In [50]:
a = np.arange(15)

In [51]:
np.set_printoptions(threshold=6)

In [52]:
a

array([ 0,  1,  2, ..., 12, 13, 14])

**24. 如何在不截断数组的前提下打印出完整的 NumPy 数组？**

难度：L1

问题：在不截断数组的前提下打印出完整的 NumPy 数组 a。

输入：
```python
np.set_printoptions(threshold=6)

a = np.arange(15)

a

#> array([ 0, 1, 2, ..., 12, 13, 14])
```
期望输出：
```python
a

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
```

In [53]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [54]:
np.set_printoptions(threshold=len(a))

In [55]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**25. 如何向 Python NumPy 导入包含数字和文本的数据集，同时保持文本不变？**

难度：L2

问题：导入 iris 数据集，保持文本不变。

In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

**26. 如何从 1 维元组数组中提取特定的列？**

难度：L2

问题：从前一个问题导入的 1 维 iris 中提取文本列 species。

输入：
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [57]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

In [58]:
iris_1d_species = np.array([i[-1] for i in iris_1d])
iris_1d_species

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      dtype='|S18')

**27. 如何将 1 维元组数组转换成 2 维 NumPy 数组？**

难度：L2

问题：忽略 species 文本字段，将 1 维 iris 转换成 2 维数组 iris_2d。

输入：
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [59]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

In [60]:
iris_2d = np.array([i.tolist()[:-1] for i in iris_1d])
iris_2d

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       ..., 
       [ 6.5,  3. ,  5.2,  2. ],
       [ 6.2,  3.4,  5.4,  2.3],
       [ 5.9,  3. ,  5.1,  1.8]])

**28. 如何计算 NumPy 数组的平均值、中位数和标准差？**

难度：L1

问题：找出 iris sepallength（第一列）的平均值、中位数和标准差。
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [61]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [62]:
mean = iris[:, 0].astype(float).mean()
median = np.median(iris[:, 0].astype(float))
std = iris[:, 0].astype(float).std()
print("mean:\t{}\nmedian:\t{}\nstd:\t{}\n".format(mean, median, std))

mean:	5.843333333333334
median:	5.8
std:	0.8253012917851409



**29. 如何归一化数组，使值的范围在 0 和 1 之间？**

难度：L2

问题：创建 iris sepallength 的归一化格式，使其值在 0 到 1 之间。

输入：
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
```

In [63]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [64]:
test = (sepallength - sepallength.min())/ (sepallength.max() - sepallength.min())

**30. 如何计算 softmax 分数？**

难度：L3

问题：计算 sepallength 的 softmax 分数。
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
```
**sofmax公式:**
$$\sigma(z_i) = \frac{e^{z_i}}{\sum{e^{z_i}}} $$

In [65]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [66]:
softmax_array = np.exp(sepallength)/np.exp(sepallength).sum()
softmax_array

array([ 0.002,  0.002,  0.001, ...,  0.009,  0.007,  0.005])

**31. 如何找到 NumPy 数组的百分数？**

难度：L1

问题：找出 iris sepallength（第一列）的第 5 个和第 95 个百分数。
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
```

In [67]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [68]:
np.percentile(sepallength, q=[5, 95])

array([ 4.6  ,  7.255])

**32. 如何在数组的随机位置插入值？**

难度：L2

问题：在 iris_2d 数据集中的 20 个随机位置插入 np.nan 值。
```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [69]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [70]:
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ..., 
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

**33. 如何在 NumPy 数组中找出缺失值的位置？**

难度：L2

问题：在 iris_2d 的 sepallength（第一列）中找出缺失值的数目和位置。
```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')

iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [71]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')

iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [72]:
# cannot compare np.nan with np.nan using "=="
np.nan == np.nan

False

In [73]:
# np.isnan should be used
np.isnan(np.nan)

True

In [74]:
positions = np.where(np.isnan(iris_2d[:,0]))
numbers = len(positions[0])
print("numbers:{}".format(numbers))
print("Position:\n{}".format(positions))

numbers:5
Position:
(array([13, 17, 47, 53, 91], dtype=int64),)


**34. 如何基于两个或以上条件过滤 NumPy 数组？**

难度：L3

问题：过滤 iris_2d 中满足 petallength（第三列）> 1.5 和 sepallength（第一列）< 5.0 的行。
```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [75]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [76]:
bool_mask = (iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)
iris_2d[bool_mask]

array([[ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 4.9,  2.4,  3.3,  1. ],
       [ 4.9,  2.5,  4.5,  1.7]])

**35. 如何在 NumPy 数组中删除包含缺失值的行？**

难度：L3

问题：选择 iris_2d 中不包含 nan 值的行。
```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [77]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


In [78]:
boolean_mask1 = np.isnan(iris_2d)
boolean_mask = ~boolean_mask1.any(axis=1)
iris_2d[boolean_mask]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       ..., 
       [ 6.5,  3. ,  5.2,  2. ],
       [ 6.2,  3.4,  5.4,  2.3],
       [ 5.9,  3. ,  5.1,  1.8]])

**36. 如何找出 NumPy 数组中两列之间的关联性？**

难度：L2

问题：找出 iris_2d 中 SepalLength（第一列）和 PetalLength（第三列）之间的关联性。
```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [79]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [80]:
# 相关系数
np.corrcoef(iris_2d[:,0], iris_2d[:,2])[0,1]

0.87175415730487138

**37. 如何确定给定数组是否有空值？**

难度：L2

问题：确定 iris_2d 是否有缺失值。

```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [81]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [82]:
np.isnan(iris_2d).any()

False

**38. 如何在 NumPy 数组中将所有缺失值替换成 0？**

难度：L2

问题：在 NumPy 数组中将所有 nan 替换成 0。
```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [83]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [84]:
iris_2d[np.isnan(iris_2d)]=0

**39. 如何在 NumPy 数组中找出唯一值的数量？**

难度：L2

问题：在 iris 的 species 列中找出唯一值及其数量。
```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [85]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [86]:
species, count = np.unique(iris[:,-1], return_counts=True)
for s, c in zip(species, count):
    print("{}:{}".format(s, c))

b'Iris-setosa':50
b'Iris-versicolor':50
b'Iris-virginica':50


**40. 如何将一个数值转换为一个类别（文本）数组？**

难度：L2

问题：将 iris_2d 的 petallength（第三列）转换以构建一个文本数组，按如下规则进行转换：

Less than 3 –> ‘small’

3-5 –> 'medium'

'>=5 –> 'large'
```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [87]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [88]:
label = np.array(["small", "medium", "large"])
label[np.digitize(iris[:,2].astype(float), [3, 5]).tolist()]

array(['small', 'small', 'small', ..., 'large', 'large', 'large'],
      dtype='<U6')

**41. 如何基于 NumPy 数组现有列创建一个新的列？**

难度：L2

问题：为 iris_2d 中的 volume 列创建一个新的列，volume 指 (pi x petallength x sepal_length^2)/3。
```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [89]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [90]:
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3
volume = volume[:, np.newaxis]
np.hstack((iris_2d, volume))

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa', 38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa', 35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       ..., 
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica',
        230.0693019978925],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica', 217.373078887185],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica',
        185.9100284614832]], dtype=object)

**42. 如何在 NumPy 中执行概率采样？**

难度：L3

问题：随机采样 iris 数据集中的 species 列，使得 setose 的数量是 versicolor 和 virginica 数量的两倍。
```python
# Import iris keeping the text column intact

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [91]:
# Import iris keeping the text column intact

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [92]:
species = np.unique(iris[:,4])
np.random.choice(species, 100, [0.5, 0.25, 0.25])

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-versicolor'], dtype=object)

**43. 如何在多维数组中找到一维的第二最大值？**

难度：L2

问题：在 species setosa 的 petallength 列中找到第二最大值。
```python
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [93]:
# Input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [94]:
index = iris[:, 2].astype(float).argsort()[-2]
iris[:, 2].astype(float)[index]

6.7000000000000002

**44. 如何用给定列将 2 维数组排序？**

难度：L2

问题：基于 sepallength 列将 iris 数据集排序。
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [95]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [96]:
index_order = iris[:, 0].astype(float).argsort()
iris[index_order]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       ..., 
       [b'7.7', b'3.8', b'6.7', b'2.2', b'Iris-virginica'],
       [b'7.7', b'3.0', b'6.1', b'2.3', b'Iris-virginica'],
       [b'7.9', b'3.8', b'6.4', b'2.0', b'Iris-virginica']], dtype=object)

**45. 如何在 NumPy 数组中找到最频繁出现的值？**

难度：L1

问题：在 iris 数据集中找到 petallength（第三列）中最频繁出现的值。
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [97]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [98]:
unique, unique_counts = np.unique(iris[:, 2], return_counts=True)
index = unique_counts.argsort()[-1]
unique[index]

b'1.5'

**46. 如何找到第一个大于给定值的数的位置？**

难度：L2 

问题：在 iris 数据集的 petalwidth（第四列）中找到第一个值大于 1.0 的数的位置。
```python
# Input:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [99]:
# Input:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [100]:
np.where(iris[:, 3].astype(float) > 1.0)[0][0]

50

In [101]:
(iris[:, 3].astype(float) > 1.0).argmax()

50

**47. 如何将数组中所有大于给定值的数替换为给定的 cutoff 值？**

难度：L2

问题：对于数组 a，将所有大于 30 的值替换为 30，将所有小于 10 的值替换为 10。

输入：
```python
np.random.seed(100)

np.random.uniform(1,50, 20)
```

In [102]:
np.random.seed(100)

input_data = np.random.uniform(1,50, 20)

In [103]:
np.clip(input_data, 10, 30)

array([ 27.627,  14.64 ,  21.801, ...,  10.   ,  30.   ,  14.43 ])

**48. 如何在 NumPy 数组中找到 top-n 数值的位置？**

难度：L2

问题：在给定数组 a 中找到 top-5 最大值的位置。
```python
np.random.seed(100)

a = np.random.uniform(1,50, 20)
```

In [104]:
np.random.seed(100)

a = np.random.uniform(1,50, 20)

In [105]:
a.argsort()[::-1][:5]

array([15, 10,  3,  7, 18], dtype=int64)

**49. 如何逐行计算数组中所有值的数量？**

难度：L4

问题：逐行计算唯一值的数量。

输入：
```python
np.random.seed(100)

arr = np.random.randint(1,11,size=(6, 10))

arr

> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],

>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],

>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],

>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],

>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],

>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```
期望输出：
```python
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],

> [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],

> [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],

> [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],

> [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],

> [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```
输出包含 10 个列，表示从 1 到 10 的数字。这些数值分别代表每一行的计数数量。例如，Cell(0,2) 中有值 2，这意味着，数字 3 在第一行出现了两次。

In [106]:
np.random.seed(100)

arr = np.random.randint(1,11,size=(6, 10))

arr

array([[ 9,  9,  4, ...,  3,  6,  3],
       [ 3,  3,  2, ..., 10,  7,  3],
       [ 5,  2,  6, ...,  8,  2,  2],
       [ 8,  8,  1, ...,  3,  6,  9],
       [ 2,  1,  8, ...,  3,  6,  2],
       [ 9,  2,  6, ...,  6,  1, 10]])

In [107]:
np.apply_along_axis(lambda x:np.histogram(x, [i+1 for i in range(11)])[0], 1, arr)

array([[1, 0, 2, ..., 2, 2, 0],
       [2, 1, 3, ..., 0, 1, 1],
       [0, 3, 0, ..., 1, 0, 0],
       [1, 0, 2, ..., 2, 1, 2],
       [2, 2, 2, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 2, 1]], dtype=int64)

**50. 如何将 array_of_arrays 转换为平面 1 维数组？**

难度：L2

问题：将 array_of_arrays 转换为平面线性 1 维数组。
```python
# Input:

arr1 = np.arange(3)

arr2 = np.arange(3,7)

arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])

array_of_arrays#> array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])], dtype=object)
```
期望输出：
```python
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [108]:
# Input:

arr1 = np.arange(3)

arr2 = np.arange(3,7)

arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])

array_of_arrays#> array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])], dtype=object)

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])], dtype=object)

In [109]:
np.concatenate(array_of_arrays)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**51. 如何为 NumPy 数组生成 one-hot 编码？**

难度：L4

问题：计算 one-hot 编码。

输入：
```python
np.random.seed(101) 

arr = np.random.randint(1,4, size=6)

arr

#> array([2, 3, 2, 2, 2, 1])
```
输出：
```python
#> array([[ 0.,  1.,  0.],

#>        [ 0.,  0.,  1.],

#>        [ 0.,  1.,  0.],

#>        [ 0.,  1.,  0.],

#>        [ 0.,  1.,  0.],

#>        [ 1.,  0.,  0.]])
```

In [110]:
np.random.seed(101) 

arr = np.random.randint(1,4, size=6)

arr

array([2, 3, 2, 2, 2, 1])

In [111]:
np.eye(3)[arr-1]

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.]])

**52. 如何创建由类别变量分组确定的一维数值？**

难度：L3

问题：创建由类别变量分组的行数。使用以下来自 iris species 的样本作为输入。

输入：
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)

species_small = np.sort(np.random.choice(species, size=20))

species_small

#> array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',

#>        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',

#>        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',

#>        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',

#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',

#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],

#>       dtype='<U15')
```
期望输出：
```python
#> [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]
```

In [112]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)

species_small = np.sort(np.random.choice(species, size=20))

species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', ..., 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'],
      dtype='<U15')

In [113]:
_, num=np.unique(species_small, return_counts=True)
[i for k in num for i in range(k)]

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8]

**53. 如何基于给定的类别变量创建分组 id？**

难度：L4

问题：基于给定的类别变量创建分组 id。使用以下来自 iris species 的样本作为输入。

输入：
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)

species_small = np.sort(np.random.choice(species, size=20))

species_small

#> array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',

#>        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',

#>        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',

#>        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',

#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',

#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],

#>       dtype='<U15')
```
期望输出：
```python
#> [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]
```

In [114]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)

species_small = np.sort(np.random.choice(species, size=20))

species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', ..., 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'],
      dtype='<U15')

In [115]:
idmap = {name:id for id, name in enumerate(np.unique(species_small))}
[idmap[specie] for specie in species_small]

[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]

**54. 如何使用 NumPy 对数组中的项进行排序？**

难度：L2

问题：为给定的数值数组 a 创建排序。

输入：
```python
np.random.seed(10)

a = np.random.randint(20, size=10)

print(a)

#> [ 9 4 15 0 17 16 17 8 9 0]
```

期望输出：
```python
[4 2 6 0 8 7 9 3 5 1]
```

In [116]:
np.random.seed(10)

a = np.random.randint(20, size=10)

print(a)

[ 9  4 15  0 17 16 17  8  9  0]


In [117]:
a.argsort().argsort()

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1], dtype=int64)

**55. 如何使用 NumPy 对多维数组中的项进行排序？**

难度：L3

问题：给出一个数值数组 a，创建一个形态相同的排序数组。

输入：
```python
np.random.seed(10)

a = np.random.randint(20, size=[2,5])

print(a)

#> [[ 9 4 15 0 17]#> [16 17 8 9 0]]
```
期望输出：
```python
#> [[4 2 6 0 8]

#> [7 9 3 5 1]]
```

In [118]:
np.random.seed(10)

a = np.random.randint(20, size=[2,5])

print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [119]:
a.ravel().argsort().argsort().reshape(a.shape)

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]], dtype=int64)

**56. 如何在 2 维 NumPy 数组中找到每一行的最大值？**

难度：L2

问题：在给定数组中找到每一行的最大值。
```python
np.random.seed(100)

a = np.random.randint(1,10, [5,3])

a

#> array([[9, 9, 4],

#>        [8, 8, 1],

#>        [5, 3, 6],

#>        [3, 3, 3],

#>        [2, 1, 9]])
```

In [120]:
np.random.seed(100)

a = np.random.randint(1,10, [5,3])

a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [121]:
a.max(axis=1)

array([9, 8, 6, 3, 9])

**57. 如何计算 2 维 NumPy 数组每一行的 min-by-max？**

难度：L3

问题：给定一个 2 维 NumPy 数组，计算每一行的 min-by-max。
```python
np.random.seed(100)

a = np.random.randint(1,10, [5,3])

a

#> array([[9, 9, 4],

#>        [8, 8, 1],

#>        [5, 3, 6],

#>        [3, 3, 3],

#>        [2, 1, 9]])
```

In [122]:
np.random.seed(100)

a = np.random.randint(1,10, [5,3])

a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [123]:
a.min(axis=1)/a.max(axis=1)

array([ 0.444,  0.125,  0.5  ,  1.   ,  0.111])

**58. 如何在 NumPy 数组中找到重复条目？**

难度：L3

问题：在给定的 NumPy 数组中找到重复条目（从第二次出现开始），并将其标记为 True。第一次出现的条目需要标记为 False。
```python
# Input

np.random.seed(100)

a = np.random.randint(0, 5, 10)

print('Array: ', a)

#> Array: [0 0 3 0 2 4 2 2 2 2]
```
期望输出：
```python
#> [False True False True False False True True True True]
```

In [124]:
# Input

np.random.seed(100)

a = np.random.randint(0, 5, 10)

print('Array: ', a)

Array:  [0 0 3 0 2 4 2 2 2 2]


In [125]:
array = np.ones(a.shape, dtype=bool)
_, index = np.unique(a, return_index=True)
array[index] = False
array

array([False,  True, False,  True, False, False,  True,  True,  True,  True], dtype=bool)

**59. 如何找到 NumPy 的分组平均值？**

难度：L3

问题：在 2 维 NumPy 数组的类别列中找到数值的平均值。

输入：
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```
期望解：
```python
#> [[b'Iris-setosa', 3.418],

#> [b'Iris-versicolor', 2.770],

#> [b'Iris-virginica', 2.974]]
```

In [126]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [127]:
np.array([[specie,iris[iris[:,-1] == specie][:, 1].astype(float).mean()] for specie in np.unique(iris[:,-1])])

array([[b'Iris-setosa', b'3.418'],
       [b'Iris-versicolor', b'2.77'],
       [b'Iris-virginica', b'2.974']],
      dtype='|S15')

**60. 如何将 PIL 图像转换成 NumPy 数组？**

难度：L3

问题：从以下 URL 中导入图像，并将其转换成 NumPy 数组。
```python
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
```

In [128]:
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [129]:
from skimage.io import imread
img = imread(URL)

**61. 如何删除 NumPy 数组中所有的缺失值？**

难度：L2

问题：从 1 维 NumPy 数组中删除所有的 nan 值。

输入：
```python
np.array([1,2,3,np.nan,5,6,7,np.nan])
```
期望输出：
```python
array([ 1., 2., 3., 5., 6., 7.])
```

In [130]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [131]:
arr[~np.isnan(arr)]

array([ 1.,  2.,  3.,  5.,  6.,  7.])

**62. 如何计算两个数组之间的欧几里得距离？**

难度：L3

问题：计算两个数组 a 和 b 之间的欧几里得距离。

输入：
```python
a = np.array([1,2,3,4,5])

b = np.array([4,5,6,7,8])
```

In [132]:
a = np.array([1,2,3,4,5])

b = np.array([4,5,6,7,8])

In [133]:
np.linalg.norm(a-b)

6.7082039324993694

**63. 如何在一个 1 维数组中找到所有的局部极大值（peak）？**

难度：L4

问题：在 1 维数组 a 中找到所有的 peak，peak 指一个数字比两侧的数字都大。

输入：
```python
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
期望输出：
```python
#> array([2, 5])
```

In [134]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

In [135]:
np.where(np.diff(np.sign(np.diff(a)))>0)[0]

array([2, 5], dtype=int64)

**64. 如何从 2 维数组中减去 1 维数组，从 2 维数组的每一行分别减去 1 维数组的每一项？**

难度：L2

问题：从 2 维数组 a_2d 中减去 1 维数组 b_1d，即从 a_2d 的每一行分别减去 b_1d 的每一项。

输入：
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])

b_1d = np.array([1,1,1])
```
期望输出：
```python
#> [[2 2 2]

#> [2 2 2]

#> [2 2 2]]
```

In [136]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])

b_1d = np.array([1,2,3])

In [137]:
 a_2d-b_1d[:,np.newaxis]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

**65. 如何在数组中找出某个项的第 n 个重复索引？**

难度：L2

问题：找到数组 x 中数字 1 的第 5 个重复索引。
```python
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
```

In [138]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [139]:
np.where(x==1)[0][4]

8

**66. 如何将 NumPy 的 datetime64 对象（object）转换为 datetime 的 datetime 对象？**

难度：L2

问题：将 NumPy 的 datetime64 对象（object）转换为 datetime 的 datetime 对象。
```python
# Input: a numpy datetime64 object

dt64 = np.datetime64('2018-02-25 22:10:10')
```

In [140]:
# Input: a numpy datetime64 object

dt64 = np.datetime64('2018-02-25 22:10:10')

In [141]:
dt64.tolist()

datetime.datetime(2018, 2, 25, 22, 10, 10)

**67. 如何计算 NumPy 数组的移动平均数？**

难度：L3

问题：给定 1 维数组，计算 window size 为 3 的移动平均数。

输入：
```python
np.random.seed(100)

Z = np.random.randint(10, size=10)
```

In [142]:
np.random.seed(100)

Z = np.random.randint(10, size=10)

In [143]:
np.convolve(Z, np.ones(3)/3, mode="valid")

array([ 6.333,  6.   ,  5.667,  4.667,  3.667,  2.   ,  3.667,  3.   ])

**68. 给定起始数字、length 和步长，如何创建一个 NumPy 数组序列？**

难度：L2

问题：从 5 开始，创建一个 length 为 10 的 NumPy 数组，相邻数字的差是 3。

In [144]:
np.arange(5,5+10*3,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

**69. 如何在不规则 NumPy 日期序列中填充缺失日期？**

难度：L3

问题：给定一个非连续日期序列的数组，通过填充缺失的日期，使其变成连续的日期序列。

输入：
```python
# Input

dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)

print(dates)

#> ['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'

#>  '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'

#>  '2018-02-21' '2018-02-23']
```

In [145]:
# Input

dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)

print(dates)

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


In [146]:
np.arange(dates.min(), dates.max()+1)

array(['2018-02-01', '2018-02-02', '2018-02-03', ..., '2018-02-21',
       '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

**70. 如何基于给定的 1 维数组创建 strides？**

难度：L4

问题：给定 1 维数组 arr，使用 strides 生成一个 2 维矩阵，其中 window length 等于 4，strides 等于 2，例如 [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]。

输入：
```python
arr = np.arange(15) 

arr

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
```
期望输出：
```python
#> [[ 0 1 2 3]

#> [ 2 3 4 5]

#> [ 4 5 6 7]

#> [ 6 7 8 9]

#> [ 8 9 10 11]

#> [10 11 12 13]]
```

In [147]:
arr = np.arange(15) 

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [148]:
strides = 2
width = 4
window = np.arange(width)
np.array([arr[window + i] for i in range(0, len(arr)-width, strides)])

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])